apiVersion: v1
kind: Pod

metadata:
  name: backend1
  labels:
    app: backend

spec:
  containers:
    - name: backend
      image: docker.io/cimbonda/backend-workshop:v1
      ports:
        - containerPort: 8085
          protocol: TCP


---

apiVersion: v1
kind: Pod

metadata:
  name: backend2
  labels:
    app: backend

spec:
  containers:
    - name: backend
      image: docker.io/cimbonda/backend-workshop:v1
      ports:
        - containerPort: 8085
          protocol: TCP
