apiVersion: v1
kind: Pod

metadata:
  name: frontend1
  labels:
    app: frontend

spec:
  containers:
    - name: frontend
      image: docker.io/cimbonda/frontend-workshop:v1
      ports:
        - containerPort: 8084
          protocol: TCP

---

apiVersion: v1
kind: Pod

metadata:
  name: frontend2
  labels:
    app: frontend

spec:
  containers:
    - name: frontend
      image: docker.io/cimbonda/frontend-workshop:v1
      ports:
        - containerPort: 8084
          protocol: TCP



