apiVersion: v1
kind: Pod

metadata:
  name: frontend-backend
  labels:
    app: frontend-backend

spec:
  containers:
    - name: frontend
      image: docker.io/cimbonda/frontend-workshop:v1
      ports:
        - containerPort: 8084
          protocol: TCP
    - name: backend
      image: docker.io/cimbonda/backend-workshop:v1
      ports:
        - containerPort: 8085
          protocol: TCP

